### ISSUE TITLE
Wayland port? :)

### ISSUE THREAD

**Issue by abique** [Kintaro/wtftw#23]

**Comment by james-darkfox** [comment]
Closed "won't fix" ?

**Comment by Kintaro** [comment]
No no.  Closed as "duly noted and will create a separate milestone and branch with several independently tracked issues as soon as I start working on it.". I will reference the milestone and the issues here. But it is not relevant for the next milestone, where the major goal is stabilization. Thus this issue is closed for now. 

Closed https://github.com/Kintaro/wtftw/labels/enhancement issues are to be understood as "noted and on the list".

**Comment by vn971** [comment]
Since wtftw successfully runs on Rust-stable now, does it make sense to reopen the ticket?

> next milestone, where the major goal is stabilization. Thus this issue is closed for now.

**Comment by Kintaro** [comment]
Hm, sense, yes. But I still don't know enough about Wayland yet. And new job starts next week, so that'll take some time away. It's not forgotten, I am still aiming for this. Maybe switching my environment to wayland will put enough pressure on me, but this will have to wait a while, sorry.

If you know something about wayland, feel free to get started, I'd happily include it.

**Comment by abique** [comment]
Anyway wayland itself is not ready...

**Comment by vn971** [comment]
Sorry. Actually, Wayland is not really important for me as of today, too. Just mentioned the state of rustc-1.2 support. I guess those who're most interested should stand up and help by bits they know / care about.

**Comment by Drakulix** [comment]
I have not much wayland knowledge either, but I suggest you also look into these alternatives to writing a weston plugin:
https://github.com/Cloudef/wlc
https://github.com/michaelforney/swc

It seems to me, that wlc is a lot more actively maintained, but both are aiming for the same goal, providing a wayland compositor as a c-library to provide a starting point for window-manager-like programs for wayland. Especially tiling-based ones. Their reasoning is, that tiling in weston is not that easy to do (not sure, if that is really true).

Their APIs seem reasonably easy to understand and suited for your WindowSystem Trait (based on a quick look). Might be worth a try.
