### ISSUE TITLE
Thread <main> panicked at ...

### ISSUE THREAD

**Issue by ptrxyz** [Kintaro/wtftw#90]
I am using wtftw (latest version) together with the config from this repo. The compilation seems to work, but starting raises this error:

thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:365

Any idea how to solve this?

FYI:
# rustc --version
rustc 1.4.0

# cargo --version
cargo 0.6.0 (e1ed995 2015-10-22)

# git pull
Already up-to-date.

I checked out this repo to ~/.wtftw/ and placed config/config.rs in ~/.wtftw/src/config.rs.

**Comment by chc4** [comment]
You probably have to put `export RUST_BACKTRACE=1` in the script you start wtftw from in order to get the full stacktrace for that error.

**Comment by Kintaro** [comment]
Wait wait, you checked out the repo into .wtftw? That will clash. The .wtftw directory is for the config only. If it tries to build the config, it will fail to do so because it would end up building wtftw instead. Check out this repo into some other place, execute target/debug/wtftw, so it creates the .wtftw, then place the config.rs in there. See if that works.
