### ISSUE TITLE
Start/stop hooks

### ISSUE THREAD

**Issue by cactorium** [Kintaro/wtftw#91]
`physlock` doesn't work because wtftw doesn't register a login on the right tty, so having hooks when a wtftw session starts and exits would be a nice to fix this. Also, Merry Christmas, and thanks for the really cool WM!

**Comment by Kintaro** [comment]
I don't even know how physlock works. I'll see what I can do about the hooks, shouldn't be to hard. But basically, you can use the config function in your config.rs as a hook, as this is called when wtftw starts up (and also on refreshes unfortunately).

**Comment by cactorium** [comment]
Ah, well the gist of it is that there's two commands that need to be executed when the display session starts and ends that aren't called, and so I figured adding start/stop hooks would be a sensible way to fix it. Using the config gets the start hook, but it'd still break because of the lack of a stop hook I think. I could try to make a pull request to add the hooks, but I dunno how you'd prefer the API to be designed

**Comment by Kintaro** [comment]
Well, I'll try to figure out how to do the stop hook. Because for reloading
the config, wtftw is essentially restarted via execvp, so I'll have to find
a way to latch into the right part.
But for now, you can use the config as a start hook and the stop command
(default is mod+shift+q, also used in the sample config) as a stop hook,
kinda.

2015年12月28日(月) 15:56 cactorium <notifications@github.com>:
